name: CI-CD Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: madhu934652
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t madhu934652/cafe-website:${{ github.sha }} .
          docker tag madhu934652/cafe-website:${{ github.sha }} madhu934652/cafe-website:latest

      - name: Push Docker Images
        run: |
          docker push madhu934652/cafe-website:${{ github.sha }}
          docker push madhu934652/cafe-website:latest

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/cafe-app \
            cafe=madhu934652/cafe-website:${{ github.sha }}

      - name: Wait for Rollout
        run: |
          kubectl rollout status deployment/cafe-app

      - name: Verify Deployment
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get svc
